-- Script para popular as tabelas cities e neighborhoods
-- Execute este script no Supabase SQL Editor

-- Inserir cidades principais
INSERT INTO cities (name, state) VALUES
('Salvador', 'BA'),
('Camaçari', 'BA'),
('Candeias', 'BA'),
('Catu', 'BA'),
('Dias D''Avila', 'BA'),
('Lauro de Freitas', 'BA'),
('Mata de São João', 'BA'),
('Pojuca', 'BA'),
('São Francisco do Conde', 'BA'),
('Simões Filho', 'BA');

-- Inserir bairros de Salvador
INSERT INTO neighborhoods (name, city_id) VALUES
-- Salvador (city_id = 1)
('Acupe', 1),
('Águas Claras', 1),
('Alto da Terezinha', 1),
('Alto do Cabrito', 1),
('Alto do Peru', 1),
('Alto do Sobradinho', 1),
('Alto do Tororó', 1),
('Amaralina', 1),
('Armação', 1),
('Baixa do Fiscal', 1),
('Baixa do Sapateiro', 1),
('Barbalho', 1),
('Barra', 1),
('Barris', 1),
('Boa Viagem', 1),
('Boca do Rio', 1),
('Bonfim', 1),
('Brotas', 1),
('Cabula', 1),
('Cajazeiras', 1),
('Calabar', 1),
('Calçada', 1),
('Caminho das Árvores', 1),
('Canela', 1),
('Canto do Engenho', 1),
('Casa Blanca', 1),
('Castelo Branco', 1),
('Centro', 1),
('Chapada do Rio Vermelho', 1),
('Cidade Nova', 1),
('Comércio', 1),
('Costa Azul', 1),
('Curuzu', 1),
('Engenho Velho da Federação', 1),
('Engenho Velho de Brotas', 1),
('Fazenda Coutos', 1),
('Fazenda Grande', 1),
('Federação', 1),
('Garcia', 1),
('Graça', 1),
('Guarani', 1),
('Horto Florestal', 1),
('Imbuí', 1),
('Itacaranha', 1),
('Itapuã', 1),
('Jardim Armação', 1),
('Jardim das Margaridas', 1),
('Liberdade', 1),
('Lobato', 1),
('Mares', 1),
('Massaranduba', 1),
('Mata Escura', 1),
('Monte Serrat', 1),
('Nazaré', 1),
('Nova Brasília', 1),
('Nova Sussuarana', 1),
('Ondina', 1),
('Patamares', 1),
('Pelourinho', 1),
('Periperi', 1),
('Pernambués', 1),
('Piatã', 1),
('Pilar', 1),
('Pirajá', 1),
('Pituba', 1),
('Plataforma', 1),
('Ponta de Humaitá', 1),
('Pouco do Óleo', 1),
('Prado', 1),
('Pratigi', 1),
('Ribeira', 1),
('Rio Sena', 1),
('Rio Vermelho', 1),
('Santa Cruz', 1),
('Santa Luzia', 1),
('Santo Antônio', 1),
('Santo Antônio Além do Carmo', 1),
('São Cristóvão', 1),
('São Gonçalo', 1),
('São João do Cabrito', 1),
('São Marcos', 1),
('São Miguel', 1),
('São Rafael', 1),
('Sete de Abril', 1),
('Sete Portas', 1),
('Soledade', 1),
('Stella Maris', 1),
('Sussuarana', 1),
('Tancredo Neves', 1),
('Tororó', 1),
('Uruguai', 1),
('Valéria', 1),
('Vila Canária', 1),
('Vila Laura', 1),
('Vila Matos', 1),
('Vila Nova', 1),
('Vila Progresso', 1),
('Vila Ruy Barbosa', 1),
('Vila São José', 1),
('Vila São Luís', 1),
('Vila São Pedro', 1),
('Vila São Roque', 1),
('Vila São Sebastião', 1),
('Vila São Vicente', 1),
('Vila Santa Cruz', 1),
('Vila Santa Luzia', 1),
('Vila Santa Maria', 1),
('Vila Santa Rita', 1),
('Vila Santa Tereza', 1),
('Vila Santo Antônio', 1),
('Vila Santo Estevão', 1),
('Vila Santo Inácio', 1),
('Vila Santo Onofre', 1),
('Vila Santo Tomé', 1),
('Vila Santos', 1),
('Vila Santos Dumont', 1),
('Vila Santos Reis', 1);

-- Inserir bairros de Camaçari (city_id = 2)
INSERT INTO neighborhoods (name, city_id) VALUES
('Centro', 2),
('Parque Florestal', 2),
('Parque Satélite', 2),
('Parque Real', 2),
('Parque Verde', 2),
('Parque Limoeiro', 2),
('Parque das Mangabas', 2),
('Parque das Mangabas II', 2),
('Parque das Mangabas III', 2),
('Parque das Mangabas IV', 2),
('Parque das Mangabas V', 2),
('Parque das Mangabas VI', 2),
('Parque das Mangabas VII', 2),
('Parque das Mangabas VIII', 2),
('Parque das Mangabas IX', 2),
('Parque das Mangabas X', 2),
('Parque das Mangabas XI', 2),
('Parque das Mangabas XII', 2),
('Parque das Mangabas XIII', 2),
('Parque das Mangabas XIV', 2),
('Parque das Mangabas XV', 2),
('Parque das Mangabas XVI', 2),
('Parque das Mangabas XVII', 2),
('Parque das Mangabas XVIII', 2),
('Parque das Mangabas XIX', 2),
('Parque das Mangabas XX', 2),
('Parque das Mangabas XXI', 2),
('Parque das Mangabas XXII', 2),
('Parque das Mangabas XXIII', 2),
('Parque das Mangabas XXIV', 2),
('Parque das Mangabas XXV', 2),
('Parque das Mangabas XXVI', 2),
('Parque das Mangabas XXVII', 2),
('Parque das Mangabas XXVIII', 2),
('Parque das Mangabas XXIX', 2),
('Parque das Mangabas XXX', 2),
('Parque das Mangabas XXXI', 2),
('Parque das Mangabas XXXII', 2),
('Parque das Mangabas XXXIII', 2),
('Parque das Mangabas XXXIV', 2),
('Parque das Mangabas XXXV', 2),
('Parque das Mangabas XXXVI', 2),
('Parque das Mangabas XXXVII', 2),
('Parque das Mangabas XXXVIII', 2),
('Parque das Mangabas XXXIX', 2),
('Parque das Mangabas XL', 2),
('Parque das Mangabas XLI', 2),
('Parque das Mangabas XLII', 2),
('Parque das Mangabas XLIII', 2),
('Parque das Mangabas XLIV', 2),
('Parque das Mangabas XLV', 2),
('Parque das Mangabas XLVI', 2),
('Parque das Mangabas XLVII', 2),
('Parque das Mangabas XLVIII', 2),
('Parque das Mangabas XLIX', 2),
('Parque das Mangabas L', 2);

-- Inserir bairros de Lauro de Freitas (city_id = 6)
INSERT INTO neighborhoods (name, city_id) VALUES
('Centro', 6),
('Vila Praiana', 6),
('Portão', 6),
('Buraquinho', 6),
('Vilas do Atlântico', 6),
('Ipitanga', 6),
('Capiarara', 6),
('Areia Branca', 6),
('Quingoma', 6),
('Itinga', 6),
('Rio do Có', 6),
('Rio do Có II', 6),
('Rio do Có III', 6),
('Rio do Có IV', 6),
('Rio do Có V', 6),
('Rio do Có VI', 6),
('Rio do Có VII', 6),
('Rio do Có VIII', 6),
('Rio do Có IX', 6),
('Rio do Có X', 6),
('Rio do Có XI', 6),
('Rio do Có XII', 6),
('Rio do Có XIII', 6),
('Rio do Có XIV', 6),
('Rio do Có XV', 6),
('Rio do Có XVI', 6),
('Rio do Có XVII', 6),
('Rio do Có XVIII', 6),
('Rio do Có XIX', 6),
('Rio do Có XX', 6),
('Rio do Có XXI', 6),
('Rio do Có XXII', 6),
('Rio do Có XXIII', 6),
('Rio do Có XXIV', 6),
('Rio do Có XXV', 6),
('Rio do Có XXVI', 6),
('Rio do Có XXVII', 6),
('Rio do Có XXVIII', 6),
('Rio do Có XXIX', 6),
('Rio do Có XXX', 6),
('Rio do Có XXXI', 6),
('Rio do Có XXXII', 6),
('Rio do Có XXXIII', 6),
('Rio do Có XXXIV', 6),
('Rio do Có XXXV', 6),
('Rio do Có XXXVI', 6),
('Rio do Có XXXVII', 6),
('Rio do Có XXXVIII', 6),
('Rio do Có XXXIX', 6),
('Rio do Có XL', 6),
('Rio do Có XLI', 6),
('Rio do Có XLII', 6),
('Rio do Có XLIII', 6),
('Rio do Có XLIV', 6),
('Rio do Có XLV', 6),
('Rio do Có XLVI', 6),
('Rio do Có XLVII', 6),
('Rio do Có XLVIII', 6),
('Rio do Có XLIX', 6),
('Rio do Có L', 6); 