// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuuoizqmtvbazeyjwedb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dW9penFtdHZiYXpleWp3ZWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDk0MDUsImV4cCI6MjA2NTIyNTQwNX0.W3F_Us1smTsOkbh60TnOV7h5kj7snJfcVPccNYMbnzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);