// Re-exportações dos tipos RH do arquivo principal types.ts
export type {
  Employee,
  EmployeeInsert,
  EmployeeUpdate,
  Position,
  PositionInsert,
  PositionUpdate,
  TimeRecord,
  TimeRecordInsert,
  TimeRecordUpdate,
  WorkSchedule,
  WorkScheduleInsert,
  WorkScheduleUpdate,
  Benefit,
  BenefitInsert,
  BenefitUpdate,
  Payroll,
  PayrollInsert,
  PayrollUpdate,
  Vacation,
  VacationInsert,
  VacationUpdate,
  MedicalCertificate,
  MedicalCertificateInsert,
  MedicalCertificateUpdate,
  ESocialEvent,
  ESocialEventInsert,
  ESocialEventUpdate,
  Recruitment,
  RecruitmentInsert,
  RecruitmentUpdate,
  Training,
  TrainingInsert,
  TrainingUpdate
} from './rh-types';
